apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: logsage-operator
  labels:
    app.kubernetes.io/name: logsage-operator
    app.kubernetes.io/instance: {{ .Release.Name }}
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "events"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: logsage-operator
  labels:
    app.kubernetes.io/name: logsage-operator
    app.kubernetes.io/instance: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: logsage-operator
subjects:
  - kind: ServiceAccount
    name: logsage-operator
    namespace: {{ .Release.Namespace }}
